version: "3.9"

services:
  db:
    image: postgres:15
    container_name: group_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: group_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
